### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/strong-testimonials-theme#2]
The image is not displayed on the page : https://image.prntscr.com/image/lhH5ccH0RIKyQRBCUkr0Yg.png (Edge, Chrome,Opera)

Mozila : https://prnt.sc/t2ol0x 

Needs to be checked also on responsive devices after the image is added.

It can be tested here for example : https://strongtestimonials.com/demos/form-examples/in-a-popup-window/

**Comment by razvanaldea89** [comment]
Location was not right. The theme directory was missing a `-theme` in the name
